In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
self_annotation_multimodal = pd.read_excel('datasets/ECG_GSR_Emotions/Self-Annotation Labels/Self-annotation Multimodal_Use.xlsx')
self_annotation_multimodal['annotation'] = 'M'
self_annotation_multimodal.rename(columns = {'V_Label':'Valence', 'A_Label':'Arousal', 'Four_Labels':'Four_Label'}, inplace = True)
self_annotation_multimodal

,Participant Id,Session ID,Video ID,Name,Age,Gender,Valence level,Arousal level,Dominance level,Happy,...,Anger,Neutral,Disgust,Surprised,Familiarity Score,Emotion,Valence,Arousal,Four_Label,annotation
0,1,1,1,M_M,13,Female,8,0,0,High,...,VeryLow,VeryLow,VeryLow,VeryLow,Never watched,Happy,HV,LA,HVLA,M
1,1,1,2,M_M,13,Female,4,0,0,VeryLow,...,VeryLow,VeryLow,VeryLow,VeryLow,NaN,Sad,LV,LA,LVLA,M
2,1,1,2,M_M,13,Female,4,0,0,VeryLow,...,VeryLow,VeryLow,VeryLow,Low,NaN,Surprise,LV,LA,LVLA,M
3,1,1,4,M_M,13,Female,9,0,0,VeryHigh,...,VeryLow,VeryLow,VeryLow,VeryLow,NaN,Happy,HV,LA,HVLA,M
4,1,1,5,M_M,13,Female,0,9,0,VeryLow,...,VeryLow,VeryLow,VeryHigh,VeryLow,NaN,Disgust,LV,HA,LVHA,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,12,3,3,Q_M,11,Male,4,9,0,VeryLow,...,VeryLow,VeryLow,VeryLow,VeryLow,Never watched,Mixed,LV,HA,LVHA,M
248,12,3,4,Q_M,11,Male,4,0,0,High,...,VeryLow,Moderate,VeryLow,Moderate,Never watched,Happy,LV,LA,LVLA,M
249,12,3,5,Q_M,11,Male,4,0,0,Moderate,...,Low,VeryLow,VeryLow,Moderate,Never watched,Mixed,LV,LA,LVLA,M
250,12,3,6,Q_M,11,Male,2,7,2,VeryLow,...,VeryHigh,Low,VeryLow,Low,Never watched,Anger,LV,HA,LVHA,M
251,12,3,7,Q_M,11,Male,2,3,3,VeryLow,...,Low,Low,VeryLow,Moderate,Never watched,Fear,LV,LA,LVLA,M

In [20]:
dummies1 = pd.get_dummies(self_annotation_multimodal.Gender)
 
# Concatenate the dummies to original dataframe
merged1 = pd.concat([self_annotation_multimodal.iloc[:, :5], dummies1, self_annotation_multimodal.iloc[:, 6:]], axis='columns')
merged1

,Participant Id,Session ID,Video ID,Name,Age,Female,Male,Valence level,Arousal level,Dominance level,...,Anger,Neutral,Disgust,Surprised,Familiarity Score,Emotion,Valence,Arousal,Four_Label,annotation
0,1,1,1,M_M,13,1,0,8,0,0,...,VeryLow,VeryLow,VeryLow,VeryLow,Never watched,Happy,HV,LA,HVLA,M
1,1,1,2,M_M,13,1,0,4,0,0,...,VeryLow,VeryLow,VeryLow,VeryLow,NaN,Sad,LV,LA,LVLA,M
2,1,1,2,M_M,13,1,0,4,0,0,...,VeryLow,VeryLow,VeryLow,Low,NaN,Surprise,LV,LA,LVLA,M
3,1,1,4,M_M,13,1,0,9,0,0,...,VeryLow,VeryLow,VeryLow,VeryLow,NaN,Happy,HV,LA,HVLA,M
4,1,1,5,M_M,13,1,0,0,9,0,...,VeryLow,VeryLow,VeryHigh,VeryLow,NaN,Disgust,LV,HA,LVHA,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,12,3,3,Q_M,11,0,1,4,9,0,...,VeryLow,VeryLow,VeryLow,VeryLow,Never watched,Mixed,LV,HA,LVHA,M
248,12,3,4,Q_M,11,0,1,4,0,0,...,VeryLow,Moderate,VeryLow,Moderate,Never watched,Happy,LV,LA,LVLA,M
249,12,3,5,Q_M,11,0,1,4,0,0,...,Low,VeryLow,VeryLow,Moderate,Never watched,Mixed,LV,LA,LVLA,M
250,12,3,6,Q_M,11,0,1,2,7,2,...,VeryHigh,Low,VeryLow,Low,Never watched,Anger,LV,HA,LVHA,M
251,12,3,7,Q_M,11,0,1,2,3,3,...,Low,Low,VeryLow,Moderate,Never watched,Fear,LV,LA,LVLA,M

In [21]:
self_annotation_singlemodal = pd.read_excel('datasets/ECG_GSR_Emotions/Self-Annotation Labels/Self-annotation Single Modal_Use.xlsx')
self_annotation_multimodal['annotation'] = 'S'
self_annotation_singlemodal

,Participant Id,Session Id,Video Id,Name,Age,Male,Valence level,Arousal level,Dominance level,Happy,...,Fear,Anger,Neutral,Disgust,Surprised,Familiarity Score,Emotion,Valence,Arousal,Four_Label
0,1,1,1,M_W,21,Female,6,0,0,Moderate,...,VeryLow,VeryLow,VeryHigh,VeryLow,VeryLow,5,Neutral,HV,LA,HVLA
1,1,1,2,M_W,21,Female,2,4,2,VeryLow,...,Low,VeryHigh,VeryLow,Moderate,Moderate,Never watched,Anger,LV,LA,LVLA
2,1,1,3,M_W,21,Female,7,6,6,Moderate,...,VeryLow,Low,Moderate,VeryLow,Moderate,Never watched,Mixed,HV,HA,HVHA
3,1,1,4,M_W,21,Female,7,3,4,Moderate,...,VeryLow,VeryLow,Low,VeryLow,Low,Never watched,Mixed,HV,LA,HVLA
4,1,1,5,M_W,21,Female,0,8,8,VeryLow,...,VeryLow,High,VeryLow,VeryHigh,High,Never watched,Disgust,LV,HA,LVHA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,12,1,3,Ah_D,14,Male,9,0,9,VeryHigh,...,Low,VeryLow,VeryLow,VeryLow,VeryLow,Never watched,Happy,HV,LA,HVLA
150,12,1,4,Ah_D,14,Male,4,7,0,VeryHigh,...,High,Moderate,VeryLow,VeryLow,VeryLow,Never watched,Happy,LV,HA,LVHA
151,12,1,5,Ah_D,14,Male,0,9,0,VeryLow,...,VeryLow,High,VeryLow,VeryHigh,VeryLow,Never watched,Disgust,LV,HA,LVHA
152,12,1,6,Ah_D,14,Male,0,9,0,VeryLow,...,VeryLow,VeryHigh,VeryLow,VeryLow,VeryLow,Never watched,Anger,LV,HA,LVHA
153,12,1,7,Ah_D,14,Male,0,0,0,VeryLow,...,VeryHigh,VeryLow,VeryLow,VeryLow,VeryLow,Never watched,Fear,LV,LA,LVLA

In [22]:
dummies2 = pd.get_dummies(self_annotation_singlemodal.Male)
 
# Concatenate the dummies to original dataframe
merged2 = pd.concat([self_annotation_singlemodal.iloc[:, :5], dummies2, self_annotation_singlemodal.iloc[:, 6:]], axis='columns')
merged2

,Participant Id,Session Id,Video Id,Name,Age,Female,Male,Valence level,Arousal level,Dominance level,...,Fear,Anger,Neutral,Disgust,Surprised,Familiarity Score,Emotion,Valence,Arousal,Four_Label
0,1,1,1,M_W,21,1,0,6,0,0,...,VeryLow,VeryLow,VeryHigh,VeryLow,VeryLow,5,Neutral,HV,LA,HVLA
1,1,1,2,M_W,21,1,0,2,4,2,...,Low,VeryHigh,VeryLow,Moderate,Moderate,Never watched,Anger,LV,LA,LVLA
2,1,1,3,M_W,21,1,0,7,6,6,...,VeryLow,Low,Moderate,VeryLow,Moderate,Never watched,Mixed,HV,HA,HVHA
3,1,1,4,M_W,21,1,0,7,3,4,...,VeryLow,VeryLow,Low,VeryLow,Low,Never watched,Mixed,HV,LA,HVLA
4,1,1,5,M_W,21,1,0,0,8,8,...,VeryLow,High,VeryLow,VeryHigh,High,Never watched,Disgust,LV,HA,LVHA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,12,1,3,Ah_D,14,0,1,9,0,9,...,Low,VeryLow,VeryLow,VeryLow,VeryLow,Never watched,Happy,HV,LA,HVLA
150,12,1,4,Ah_D,14,0,1,4,7,0,...,High,Moderate,VeryLow,VeryLow,VeryLow,Never watched,Happy,LV,HA,LVHA
151,12,1,5,Ah_D,14,0,1,0,9,0,...,VeryLow,High,VeryLow,VeryHigh,VeryLow,Never watched,Disgust,LV,HA,LVHA
152,12,1,6,Ah_D,14,0,1,0,9,0,...,VeryLow,VeryHigh,VeryLow,VeryLow,VeryLow,Never watched,Anger,LV,HA,LVHA
153,12,1,7,Ah_D,14,0,1,0,0,0,...,VeryHigh,VeryLow,VeryLow,VeryLow,VeryLow,Never watched,Fear,LV,LA,LVLA

In [23]:
self_annotation_frames = [merged1, merged2]
merged_dataframe = pd.concat(self_annotation_frames)
merged_dataframe

,Participant Id,Session ID,Video ID,Name,Age,Female,Male,Valence level,Arousal level,Dominance level,...,Disgust,Surprised,Familiarity Score,Emotion,Valence,Arousal,Four_Label,annotation,Session Id,Video Id
0,1,1.0,1.0,M_M,13,1,0,8,0,0,...,VeryLow,VeryLow,Never watched,Happy,HV,LA,HVLA,M,NaN,NaN
1,1,1.0,2.0,M_M,13,1,0,4,0,0,...,VeryLow,VeryLow,NaN,Sad,LV,LA,LVLA,M,NaN,NaN
2,1,1.0,2.0,M_M,13,1,0,4,0,0,...,VeryLow,Low,NaN,Surprise,LV,LA,LVLA,M,NaN,NaN
3,1,1.0,4.0,M_M,13,1,0,9,0,0,...,VeryLow,VeryLow,NaN,Happy,HV,LA,HVLA,M,NaN,NaN
4,1,1.0,5.0,M_M,13,1,0,0,9,0,...,VeryHigh,VeryLow,NaN,Disgust,LV,HA,LVHA,M,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,12,NaN,NaN,Ah_D,14,0,1,9,0,9,...,VeryLow,VeryLow,Never watched,Happy,HV,LA,HVLA,NaN,1.0,3.0
150,12,NaN,NaN,Ah_D,14,0,1,4,7,0,...,VeryLow,VeryLow,Never watched,Happy,LV,HA,LVHA,NaN,1.0,4.0
151,12,NaN,NaN,Ah_D,14,0,1,0,9,0,...,VeryHigh,VeryLow,Never watched,Disgust,LV,HA,LVHA,NaN,1.0,5.0
152,12,NaN,NaN,Ah_D,14,0,1,0,9,0,...,VeryLow,VeryLow,Never watched,Anger,LV,HA,LVHA,NaN,1.0,6.0
153,12,NaN,NaN,Ah_D,14,0,1,0,0,0,...,VeryLow,VeryLow,Never watched,Fear,LV,LA,LVLA,NaN,1.0,7.0

In [24]:
train_d_frame = merged_dataframe.copy().drop(['Video ID', 'Happy', 'Sad', 'Fear',
                                        'Anger', 'Neutral', 'Disgust', 'Surprised', 'Four_Label', 'annotation'
                                       ], axis = 1)
# train_d_frame.drop(colummns=[c for c in train_d_frame.columns if 'Unnamed' in c], )
for x in train_d_frame.columns:
    if 'Unnamed' in x:
        train_d_frame.drop(columns=x, inplace=True)

train_d_frame

,Participant Id,Session ID,Name,Age,Female,Male,Valence level,Arousal level,Dominance level,Familiarity Score,Emotion,Valence,Arousal,Session Id,Video Id
0,1,1.0,M_M,13,1,0,8,0,0,Never watched,Happy,HV,LA,NaN,NaN
1,1,1.0,M_M,13,1,0,4,0,0,NaN,Sad,LV,LA,NaN,NaN
2,1,1.0,M_M,13,1,0,4,0,0,NaN,Surprise,LV,LA,NaN,NaN
3,1,1.0,M_M,13,1,0,9,0,0,NaN,Happy,HV,LA,NaN,NaN
4,1,1.0,M_M,13,1,0,0,9,0,NaN,Disgust,LV,HA,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,12,NaN,Ah_D,14,0,1,9,0,9,Never watched,Happy,HV,LA,1.0,3.0
150,12,NaN,Ah_D,14,0,1,4,7,0,Never watched,Happy,LV,HA,1.0,4.0
151,12,NaN,Ah_D,14,0,1,0,9,0,Never watched,Disgust,LV,HA,1.0,5.0
152,12,NaN,Ah_D,14,0,1,0,9,0,Never watched,Anger,LV,HA,1.0,6.0
153,12,NaN,Ah_D,14,0,1,0,0,0,Never watched,Fear,LV,LA,1.0,7.0

**training**

In [ ]:
features = ['Age', 'Female', 'Male', 'Arousal level', 'Arousal']
cl = { 'LA':0, 'HA':1}
train_d_frame['Arousal'] = train_d_frame['Arousal'].map(cl)
X = train_d_frame[features]
y = train_d_frame.iloc[:, 10]

In [ ]:
# tr = train_d_frame[['Arousal level', 'Valence level']]
# train_d_frame['Arousal level'] = train_d_frame['Arousal level'].astype(str).astype('int64')
# df_num = tr.select_dtypes(exclude=[int])
# df_num
#tr.loc[:, tr.dtypes == object]
train_d_frame

Empty DataFrame
Columns: [Participant Id, Session ID, Name, Age, Female, Male, Valence level, Arousal level, Dominance level, Familiarity Score, Emotion, Valence, Arousal, Session Id, Video Id]
Index: []

In [ ]:
train_d_frame.dtypes

Participant Id         int64
Session ID           float64
Name                  object
Age                    int64
Female                 uint8
Male                   uint8
Valence level          int64
Arousal level         object
Dominance level        int64
Familiarity Score     object
Emotion               object
Valence               object
Arousal                int64
Session Id           float64
Video Id             float64
dtype: object

In [ ]:
#Preparing the model
from sklearn.model_selection import train_test_split, GridSearchCV, KFold
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, random_state = 99)

ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

cv = KFold(n_splits=10, random_state=1, shuffle=True)

grid_params_knn = { 'n_neighbors' : range(1,20)}

gs = GridSearchCV(KNeighborsClassifier(), grid_params_knn, cv=cv)
gs.fit(X_train, y_train)
gs.best_params_

ValueError:
All the 190 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
190 fits failed with the following error:
Traceback (most recent call last):
  File "c:\ProgramData\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\ProgramData\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py", line 215, in fit
    return self._fit(X, y)
  File "c:\ProgramData\anaconda3\lib\site-packages\sklearn\neighbors\_base.py", line 454, in _fit
    X, y = self._validate_data(
  File "c:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "c:\ProgramData\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 1106, in check_X_y
    X = check_array(
  File "c:\ProgramData\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "c:\ProgramData\anaconda3\lib\site-packages\sklearn\utils\_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "c:\ProgramData\anaconda3\lib\site-packages\pandas\core\generic.py", line 2070, in __array__
    return np.asarray(self._values, dtype=dtype)
ValueError: could not convert string to float: '⁸'